Vagrant.configure('2') do |config|
    config.vm.box = 'precise32'
    config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

    config.vm.network :forwarded_port, guest: 80, host: 8000
    config.vm.provision :shell, :path => 'provision/setup.sh'

    # Use vagrant-cachier's cache to speed up provisioning
    config.cache.auto_detect = true
end
